### ISSUE TITLE
Elastalert not handle unkonwn id for notifiers

### ISSUE THREAD

**Issue by rvadim** [rvadim/elastalert-k8s-automation#29]
Admin part:
```
es_host: <host>
es_port: 9200
run_every:
  seconds: 60
writeback_index: logstash-kube-spb-test
buffer_time:
  minutes: 45
alert_configs:
  slack:
    default: to_vadim
    configs:
      to_vadim:
        slack_webhook_url: <url>
```
User part:
```
    name: ingress-alerts
    type: frequency
    index: <index>
    use_strftime_index: true
    num_events: 1
    timeframe:
      minutes: 5
    realert:
      minutes: 0
    #include: ["@timestamp", "fingerprint", "host", "index_name", "message", "source"]
    filter:
    - query_string:
        query: 'kubernetes.namespace: ingress-nginx AND status: 500'
    alert:
      - slack
    slack_id: to_vedim <- typo
```
Error:
```
elastalert.util.EAException: Error loading file /config/rules/rule_0.yaml: Error initiating alert ['slack']: Missing required option(s): slack_webhook_url
```
